// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUwPFf53XREw1h67d9JGoh6hv6yixL6PQ',
    appId: '1:97936130174:web:1ee8e965e523941997d82f',
    messagingSenderId: '97936130174',
    projectId: 'proyecto-flut',
    authDomain: 'proyecto-flut.firebaseapp.com',
    storageBucket: 'proyecto-flut.appspot.com',
    measurementId: 'G-8BZWSMQBXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJIj9V3Wk_QgjKfkE2fP9rUPsNrVtAXDg',
    appId: '1:97936130174:android:ce7b13c995d008ff97d82f',
    messagingSenderId: '97936130174',
    projectId: 'proyecto-flut',
    storageBucket: 'proyecto-flut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAluxU7bgZZsdBviitTnyLli786N52SdZo',
    appId: '1:97936130174:ios:89e96354e60d9e1c97d82f',
    messagingSenderId: '97936130174',
    projectId: 'proyecto-flut',
    storageBucket: 'proyecto-flut.appspot.com',
    iosBundleId: 'com.flutter.flutterTrabajo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAluxU7bgZZsdBviitTnyLli786N52SdZo',
    appId: '1:97936130174:ios:78bf7bc3bd25157c97d82f',
    messagingSenderId: '97936130174',
    projectId: 'proyecto-flut',
    storageBucket: 'proyecto-flut.appspot.com',
    iosBundleId: 'com.flutter.flutterTrabajo.RunnerTests',
  );
}
